pipeline:

  serieswatcher_deploy:
    group: build
    image: plugins/docker
    repo: registry.fge.cloud/fabiangehrlicher/series-watcher
    registry: https://registry.fge.cloud
    dockerfile: Serieswatcher-go.Dockerfile
    tags:
    - 1.0.0
    - 1.0
    - 1
    - latest
    username: drone
    password: drone

  serieswatcher_database_deploy:
    group: build
    image: plugins/docker
    repo: registry.fge.cloud/fabiangehrlicher/series-watcher-database
    registry: https://registry.fge.cloud
    dockerfile: Serieswatcher-mysql.Dockerfile
    tags:
    - 1.0.0
    - 1.0
    - 1
    - latest
    username: drone
    password: drone

  deploy:
    image: appleboy/drone-ssh
    host: fge.cloud
    username: root
    port: 22
    secrets: [ ssh_password ]
    script:
      - docker pull registry.fge.cloud/fabiangehrlicher/series-watcher
      - docker pull registry.fge.cloud/fabiangehrlicher/series-watcher-database
      - cd /root/docker && ls -la
