pipeline:

  serieswatcher_deploy:
    image: plugins/docker
    repo: registry.fge.cloud/fabiangehrlicher/series-watcher
    registry: https://registry.fge.cloud
    dockerfile: Serieswatcher-go.Dockerfile
    tags:
    - 1.0.0
    - 1.0
    - 1
    - latest
    username: drone
    password: drone

  serieswatcher_database_deploy:
    image: plugins/docker
    repo: registry.fge.cloud/fabiangehrlicher/series-watcher-database
    registry: https://registry.fge.cloud
    dockerfile: Serieswatcher-mysql.Dockerfile
    tags:
    - 1.0.0
    - 1.0
    - 1
    - latest
    username: drone
    password: drone
