version: '2'
services:

  mysql:
    image: mysql:5.7
    volumes:
      - ./Ressources/Db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: serieswatcher

  go:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    links:
      - mysql
