version: '2'
services:

  mysql:
    image: mysql:5.7
    container_name: serieswatchermysql
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: series

  go:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    links:
      - mysql

volumes:
  mysql:
