-- MySQL Script generated by MySQL Workbench
-- Wed Jan 17 10:09:52 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

USE `series` ;

-- -----------------------------------------------------
-- Table `series`.`Image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `series`.`Image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Path` VARCHAR(255) NULL,
  `OriginUrl` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `series`.`Series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `series`.`Series` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(255) NULL,
  `Image_id` INT NOT NULL,
  `Seriescol` INT NULL,
  `DataProviderUrl` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Series_Image1_idx` (`Image_id` ASC),
  CONSTRAINT `fk_Series_Image1`
    FOREIGN KEY (`Image_id`)
    REFERENCES `series`.`Image` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `series`.`Provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `series`.`Provider` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL,
  `Image_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Provider_Image1_idx` (`Image_id` ASC),
  CONSTRAINT `fk_Provider_Image1`
    FOREIGN KEY (`Image_id`)
    REFERENCES `series`.`Image` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `series`.`Episode`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `series`.`Episode` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Series_id` INT NOT NULL,
  `Image_id` INT NOT NULL,
  `Episode` INT NULL,
  `Season` INT NULL,
  `Title` VARCHAR(255) NULL,
  `Description` TEXT NULL,
  `ReleaseDate` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Episode_Series1_idx` (`Series_id` ASC),
  INDEX `fk_Episode_Image1_idx` (`Image_id` ASC),
  CONSTRAINT `fk_Episode_Series1`
    FOREIGN KEY (`Series_id`)
    REFERENCES `series`.`Series` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Episode_Image1`
    FOREIGN KEY (`Image_id`)
    REFERENCES `series`.`Image` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `series`.`Credentials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `series`.`Credentials` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Password` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `series`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `series`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL,
  `Credentials_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_User_Credentials1_idx` (`Credentials_id` ASC),
  CONSTRAINT `fk_User_Credentials1`
    FOREIGN KEY (`Credentials_id`)
    REFERENCES `series`.`Credentials` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `series`.`WatchPointer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `series`.`WatchPointer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `User_id` INT NOT NULL,
  `Episode_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_WatchPointer_User_idx` (`User_id` ASC),
  INDEX `fk_WatchPointer_Episode1_idx` (`Episode_id` ASC),
  CONSTRAINT `fk_WatchPointer_User`
    FOREIGN KEY (`User_id`)
    REFERENCES `series`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WatchPointer_Episode1`
    FOREIGN KEY (`Episode_id`)
    REFERENCES `series`.`Episode` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `series`.`ThirdPartyAccount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `series`.`ThirdPartyAccount` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Provider_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  `Credentials_id` INT NOT NULL,
  `Username` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Account_Provider1_idx` (`Provider_id` ASC),
  INDEX `fk_Account_User1_idx` (`User_id` ASC),
  INDEX `fk_ThirdPartyAccount_Credentials1_idx` (`Credentials_id` ASC),
  CONSTRAINT `fk_Account_Provider1`
    FOREIGN KEY (`Provider_id`)
    REFERENCES `series`.`Provider` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Account_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `series`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ThirdPartyAccount_Credentials1`
    FOREIGN KEY (`Credentials_id`)
    REFERENCES `series`.`Credentials` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `series`.`ProviderUrl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `series`.`ProviderUrl` (
  `Episode_id` INT NOT NULL AUTO_INCREMENT,
  `Provider_id` INT NOT NULL,
  `Url` VARCHAR(100) NULL,
  PRIMARY KEY (`Episode_id`, `Provider_id`),
  INDEX `fk_Episode_has_Provider_Provider1_idx` (`Provider_id` ASC),
  INDEX `fk_Episode_has_Provider_Episode1_idx` (`Episode_id` ASC),
  CONSTRAINT `fk_Episode_has_Provider_Episode1`
    FOREIGN KEY (`Episode_id`)
    REFERENCES `series`.`Episode` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Episode_has_Provider_Provider1`
    FOREIGN KEY (`Provider_id`)
    REFERENCES `series`.`Provider` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `series`.`SeriesProvider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `series`.`SeriesProvider` (
  `Series_id` INT NOT NULL AUTO_INCREMENT,
  `Provider_id` INT NOT NULL,
  `BaseUrl` VARCHAR(255) NULL,
  PRIMARY KEY (`Series_id`, `Provider_id`),
  INDEX `fk_Series_has_Provider_Provider1_idx` (`Provider_id` ASC),
  INDEX `fk_Series_has_Provider_Series1_idx` (`Series_id` ASC),
  CONSTRAINT `fk_Series_has_Provider_Series1`
    FOREIGN KEY (`Series_id`)
    REFERENCES `series`.`Series` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Series_has_Provider_Provider1`
    FOREIGN KEY (`Provider_id`)
    REFERENCES `series`.`Provider` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `series`.`Log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `series`.`Log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Message` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `series`.`ManualAction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `series`.`ManualAction` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(255) NULL,
  `Parameter` VARCHAR(500) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
