-- MySQL Script generated by MySQL Workbench
-- Tue Jan 23 12:21:15 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema series
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema series
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `series` DEFAULT CHARACTER SET utf8 ;
USE `series` ;

-- -----------------------------------------------------
-- Table `series`.`Image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `series`.`Image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Path` VARCHAR(255) NULL,
  `OriginUrl` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `series`.`Series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `series`.`Series` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(255) NULL,
  `Image_id` INT NOT NULL,
  `ProviderUrl` VARCHAR(255) NULL,
  `ProviderType` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Series_Image_idx` (`Image_id` ASC),
  CONSTRAINT `fk_Series_Image`
    FOREIGN KEY (`Image_id`)
    REFERENCES `series`.`Image` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `series`.`Provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `series`.`Provider` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL,
  `Image_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Provider_Image_idx` (`Image_id` ASC),
  CONSTRAINT `fk_Provider_Image`
    FOREIGN KEY (`Image_id`)
    REFERENCES `series`.`Image` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `series`.`Episode`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `series`.`Episode` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Series_id` INT NOT NULL,
  `Image_id` INT NOT NULL,
  `Episode` INT NULL,
  `Season` INT NULL,
  `Title` VARCHAR(255) NULL,
  `Description` TEXT NULL,
  `ReleaseDate` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Episode_Series_idx` (`Series_id` ASC),
  INDEX `fk_Episode_Image_idx` (`Image_id` ASC),
  CONSTRAINT `fk_Episode_Series`
    FOREIGN KEY (`Series_id`)
    REFERENCES `series`.`Series` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Episode_Image`
    FOREIGN KEY (`Image_id`)
    REFERENCES `series`.`Image` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `series`.`WatchPointer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `series`.`WatchPointer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Episode_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_WatchPointer_Episode_idx` (`Episode_id` ASC),
  CONSTRAINT `fk_WatchPointer_Episode`
    FOREIGN KEY (`Episode_id`)
    REFERENCES `series`.`Episode` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `series`.`Credentials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `series`.`Credentials` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Password` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `series`.`ThirdPartyAccount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `series`.`ThirdPartyAccount` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Provider_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  `Credentials_id` INT NOT NULL,
  `Username` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Account_Provider_idx` (`Provider_id` ASC),
  INDEX `fk_ThirdPartyAccount_Credentials_idx` (`Credentials_id` ASC),
  CONSTRAINT `fk_Account_Provider`
    FOREIGN KEY (`Provider_id`)
    REFERENCES `series`.`Provider` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ThirdPartyAccount_Credentials`
    FOREIGN KEY (`Credentials_id`)
    REFERENCES `series`.`Credentials` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `series`.`Url`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `series`.`Url` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Url` VARCHAR(255) NULL,
  `Episode_id` INT NOT NULL,
  `Provider_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_EpisodeLinks_Episode_idx` (`Episode_id` ASC),
  INDEX `fk_Url_Provider_idx` (`Provider_id` ASC),
  CONSTRAINT `fk_EpisodeLinks_Episode`
    FOREIGN KEY (`Episode_id`)
    REFERENCES `series`.`Episode` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Url_Provider`
    FOREIGN KEY (`Provider_id`)
    REFERENCES `series`.`Provider` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `series`.`BaseUrl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `series`.`BaseUrl` (
  `id` INT NOT NULL,
  `Url` VARCHAR(255) NULL,
  `Series_id` INT NOT NULL,
  `Provider_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_BaseUrl_Series_idx` (`Series_id` ASC),
  INDEX `fk_BaseUrl_Provider_idx` (`Provider_id` ASC),
  CONSTRAINT `fk_BaseUrl_Series`
    FOREIGN KEY (`Series_id`)
    REFERENCES `series`.`Series` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BaseUrl_Provider`
    FOREIGN KEY (`Provider_id`)
    REFERENCES `series`.`Provider` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `series`.`ManualAction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `series`.`ManualAction` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `done` INT NULL,
  `Type` VARCHAR(45) NULL,
  `Message` VARCHAR(255) NULL,
  `Time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `series`.`Log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `series`.`Log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) NULL,
  `Message` VARCHAR(45) NULL,
  `Time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
